package StudentApp;


/**
* StudentApp/StudentAppOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/GitHub/ControlWork5/src/main/java/StudentApp.idl
* 5 ?????? 2021 ?. 18:58:09 MSK
*/

public interface StudentAppOperations 
{
  String add ();
  String udate ();
  String delete ();
  void shutdown ();
} // interface StudentAppOperations
