package StudentApp;


/**
* StudentApp/StudentApp.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/GitHub/ControlWork5/src/main/java/StudentApp.idl
* 5 ?????? 2021 ?. 18:58:09 MSK
*/

public interface StudentApp extends StudentAppOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StudentApp
