package StudentApp;


import org.omg.CORBA.Object;

/**
* StudentApp/StudentAppHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/GitHub/ControlWork5/src/main/java/StudentApp.idl
* 5 ?????? 2021 ?. 18:58:09 MSK
*/

abstract public class StudentAppHelper
{
  private static String  _id = "IDL:StudentApp/StudentApp:1.0";

  public static void insert (org.omg.CORBA.Any a, StudentApp that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static StudentApp extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (StudentAppHelper.id (), "StudentApp");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static StudentApp read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StudentAppStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, StudentApp value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static StudentApp narrow (Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StudentApp)
      return (StudentApp)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _StudentAppStub stub = new _StudentAppStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static StudentApp unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StudentApp)
      return (StudentApp)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _StudentAppStub stub = new _StudentAppStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
